#!/usr/bin/env bash

${BASH_VERSION+shopt -s extglob}
GETFILE=~/.tmp-getnet
CALCFILE=~/.tmp-getnet-calc
ASFILE=~/.tmp-getnet-as
read -d '' help <<- EOF
getnets - script get inetnums by mnt-by and mnt-lower
usage: getnets MOUNTER [SERVER]
it adds -MNT for you automatically ;)
script use RIPE NCC options so it may not work with other servers
EOF

if [[ ! $1 ]]; then
    echo "$help"
    exit 1
fi

while :; do
    case $1 in
        -h|--help)
            echo "$help"
            exit 0
            ;;
        -m|--mount)
            if [[ "$2" ]]; then
                MNT="$2"
                shift 2
                continue
            else
                echo "must specify mnt parameter for query"
                exit 1
            fi
            ;;
        -a|--as)
            if [[ "$2" ]]; then
                AS="$2"
                shift 2
                continue
            else
                echo "must specify AS for query"
                exit 1
            fi
            ;;
        -s|--server)
            if [[ "$2" ]]; then
                SRV="$2"
                shift 2
                continue
            else
                echo "must specify server for query"
                exit 1
            fi
            ;;
        -?*)
            echo "unknown option $1"
            ;;
        *)
            break
    esac

    shift
done

if [[ ! "$SRV" ]]; then 
    SRV='whois.ripe.net'
fi
if [[ -f "$GETFILE" ]]; then
    rm "$GETFILE"
fi
if [[ -f "$CALCFILE" ]]; then
    rm "$CALCFILE"
fi

mntsearch() {
    whois -h "$SRV" -T inetnum -i mnt-by "$1" | grep inetnum | awk '{print $2$3$4}' > "$GETFILE"
    whois -h "$SRV" -T inetnum -i mnt-lower "$1" | grep inetnum | awk '{print $2$3$4}' >> "$GETFILE"
    while read line; do
        ipcalc "$line" >> "$CALCFILE"
    done < "$GETFILE"
    if [[ -f "$CALCFILE" ]]; then
        grep / "$CALCFILE"
        rm "$CALCFILE"
        rm "$GETFILE"
        exit 0
    else
        echo 'Qeury return nothing'
        rm "$GETFILE"
        exit 1
    fi
}

if [[ "$MNT" && "$AS" ]]; then
    echo "can't search both AS and mnt parameter"
    exit 1
elif [[ "$MNT" ]]; then
    if [[ "$MNT" != *-@(mnt|MNT) ]]; then
        MNT="$MNT-MNT"
    else
        MNT="$MNT"
    fi
    mntsearch "$MNT"
elif [[ "$AS" ]]; then
    whois -h "$SRV" as"$AS" | grep mnt-by | grep -v RIPE | awk '{print $2}' > "$ASFILE"
    MNT=$(head -n 1 "$ASFILE")
    rm "$ASFILE"
    mntsearch "$MNT"
else
    echo "no query specified"
    exit 1
fi
