#!/usr/bin/env bash

hash whois 2>/dev/null || { echo "whois is not found" &>2; DPND=1; }
hash sed 2>/dev/null || { echo "sed is not found" &>2; DPND=1; }
hash sort 2>/dev/null || { echo "sort is not found" &>2; DPND=1; }
if [[ "$DPND" = 1 ]]; then
    echo &>2 "not all dependency met"
    exit 1
fi

read -d '' help <<- EOF
getnets - script get all inetnums of autonomous system
usage: getnets ASNUMBER
EOF

if [[ ! $1 ]]; then
    echo "$help"
    exit 1
elif [[ $1 = -h || $1 = --help ]]; then
    echo "$help"
    exit 0
elif [[ $1 -lt 1 || $1 -eq 65535 || $1 -gt 4294967294 ]]; then
    echo "invalid ASN"
    exit 1
elif [[ $1 -gt 64511 && $1 -lt 65535 ]]; then
    echo "private 16bit ASN"
    exit 1
elif [[ $1 -gt 4200000000 && $1 -lt 4294967295 ]]; then
    echo "private 32bit ASN"
    exit 1
fi

OUT=$(whois -h whois.radb.net "!gas$1" | sed '1d' | sed '$d')
IFS=' ' read -ra NET <<< "$OUT"
SNET=($(printf "%s\n" "${NET[@]}" | sort -u))
for i in "${SNET[@]}"; do
    echo "$i"
done
